# Generated by Django 5.1.6 on 2025-02-16 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calculator_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('formula', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Health Calculator',
                'verbose_name_plural': 'Health Calculators',
                'db_table': 'tools_health_calculator',
            },
        ),
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField()),
                ('result', models.JSONField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('calculator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.healthcalculator')),
            ],
            options={
                'verbose_name': 'Calculation History',
                'verbose_name_plural': 'Calculation Histories',
                'db_table': 'tools_calculation_history',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
